name: 'Nagarro_POC'  # Name of the DBT project
version: '1.0.0'  # Version of the DBT project

config-version: 2  # Config version for DBT, version 2 is the most current

profile: 'Nagarro_POC'  # Profile name defined in your profiles.yml file

# This setting specifies the default behavior for models
# You can specify a default schema, database, and materialization for your models here
model-paths: ["models"]  # Path to the models directory
analysis-paths: ["analysis"]  # Path to the analysis directory
test-paths: ["tests"]  # Path to the tests directory
seed-paths: ["seeds"]  # Path to the seeds directory

# This section specifies the directories where DBT will store the results of operations
target-path: "target"  # Where to store the compiled models, documentation, etc.

# Default materializations for different types of models
# You can override these settings per model in the models directory
models:
  Nagarro_POC:  # This defines model configurations for the jaffle_shop project
    +materialized: view  # Set the default materialization to "view"
    staging:
      +materialized: table  # Materialization for staging models, set to "table"
    marts:
      +materialized: table  # Materialization for marts models, set to "table"

# Seed configuration (for loading CSVs)
seeds:
  Nagarro_POC:
    +materialized: seed  # Load seeds as tables

# You can also include any other global configurations here, such as:

# Models configuration: Enables certain models to run only in specific environments
# Example:
# environments:
#   dev:
#     models:
#       - raw
#       - staging
#   prod:
#     models:
#       - staging
#       - marts
